name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
        - completed

jobs:

    deploy:
        runs-on: ubuntu-latest
        environment: devel
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
    
    
          - name: Download Artifact
            uses: actions/download-artifact@v3
            with:
              name: build-files

          - name: Output content
            run: ls



