name: Deploy Application

on:
  pull_request:
    branches:
      - main
      - dev
      - prod
      - stage
  push:
    branches:
      - '*'

jobs:

  deploy:
    uses: ./.github/workflows/CI.yml  
    
  deploy_dev:
    runs-on: ubuntu-latest
    needs: deploy
    environment: devel
    steps:
         - name: Checkout Repository
           uses: actions/checkout@v2
         - name: Decompress Artifact
           run: unzip build-files/dist-file.zip -d .


