name: CI

on:
  push:
    branches:
      - main
      - devel
      - stage
      - prod
      - feature*
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Formatter
        run: npm i -g prettier

      - name: Test
        run: CI=true npm test

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build

  Deploy_Dev:
    name: Deploy Development environment
    runs-on: ubuntu-latest
    environment: devel
    needs: build
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/devel'}}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: build
      - name: test artifact dowload
        run: pwd
        

      - name: Copy build to dev storage account
        uses: azure/cli@v2
        with:
         azcliversion: 2.30.0
         inlineScript: |
          az storage blob upload-batch --account-name  staticwebsitedevelsahr  --account-key ${{ secrets.AZURE_STORAGE_KEY }} --auth-mode key  -d '$web' -s ./build    
           
      
  Deploy_Stage:
    name: Deploy stage environment
    runs-on: ubuntu-latest
    environment: stage
    needs: build
    if: ${{ github.ref == 'refs/heads/stage'}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: build
        
      - name: Copy build to dev storage account
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload-batch --account-name  ${{ vars.STORAGEACCOUNT }} --account-key ${{ secrets.AZURE_STORAGE_KEY }} --auth-mode key  -d '$web' -s ./build    
   
   
  Deploy_Prod:
    name: Deploy prod environment
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    if: ${{ github.ref == 'refs/heads/prod'}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: build
        
      - name: Copy build to dev storage account
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload-batch --account-name  ${{ vars.STORAGEACCOUNT }} --account-key ${{ secrets.AZURE_STORAGE_KEY }} --auth-mode key  -d '$web' -s ./build    
           