name: CI

on:
  push:
    branches:
      - '*'
  workflow_call: 
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Formatter
        run: npm i -g prettier

      - name: Test
        run: CI=true npm test

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files