name: CI

on:
  push:
    branches:
      - '*'
  workflow_call: 
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Formatter
        run: npm i -g prettier

      - name: Test
        run: CI=true npm test

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build

      - name: Install Azure CLI
        uses: azure/setup-azure-cli@v1
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
          ARM_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}  
        with:
          azcliversion: 2.24.0
          
      - name: Copy build to storage account
        uses: azure/cli@v2
        with:
         azcliversion: 2.30.0
         inlineScript: |
          az storage blob upload-batch --acount-name  staticwebsitepggeqa --account-key ${{ secrets.ACCESS_KEY }}  --destination $web  --source build      
  
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
  
