name: Protect 
on:
    push:
        branches:
            - stage
    pull_request:
        branches:
            - stage
jobs:
    protect:
        runs-on: ubuntu-latest

        steps:
        - name: Checkut repository
          uses: action/checkout@v2
         
        - name: Check if PR is from devel branch
          run: |
           SOURCE_BRANCH=$(jq -r ".pull_request-head.ref" "$GITHUB_EVENT_PATH")  
           if [[ "$SOURCE_BRANCH" != "devel" ]]; then
            echo "Merges into stage branch are only allowed from devel branch"
            exit 1
           fi