name: 'Terraform'

on:
    workflow_dispatch:

jobs:
    terraform:
        name: 'Terraform'
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
            ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
            ARM_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}   
            ROOTH_PATH: '${{ github.workspace }}/Infra'
            TF_LOG: INFO
            TF_INPUT: false
            environment: dev
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ${{env.ROOTH_PATH}}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: 'Setup Terraform'
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.7.5


            - name: 'Terraform Init'
              id: init
              working-directory: ${{env.ROOTH_PATH}}
              run: terraform init  

            - name: 'Set workspace'
              working-directory: ${{env.ROOTH_PATH}}
              run: |
                
                terraform workspace select ${{ env.environment}} || terraform workspace new  ${{ env.environment}}       

            - name: 'Terraform plan'
              id: plan
              env:
                ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
                ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
                ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
                ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
                ARM_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}   
                ROOTH_PATH: '${{ github.workspace }}/Infra'
                working-directory: ${{env.ROOTH_PATH}}
                
              run: terraform plan --var-file prod.tfvars

            - name: 'Terraform Apply'
              env:
                ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
                ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
                ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
                ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
                ARM_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}   
                ROOTH_PATH: '${{ github.workspace }}/Infra'
                working-directory: ${{env.ROOTH_PATH}}
              run: terraform apply --var-file prod.tfvars -auto-approve 
                         

