name: 'Terraform'

on:
    workflow_dispatch:

jobs:
    terraform:
        name: 'Terraform'
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
            ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
            ARM_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}   
            ROOTH_PATH: '${{ github.workspace }}/Infra'
        runs-on: ubuntu-latest
        environment: dev
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: 'Terraform format'
              uses: hashicorp/terraform-github-action@master
              with:
                tf_action_version: 1.7.5
                tf_action_subcommand: 'fmt'
                tf_action_working_dir: ${{env.ROOTH_PATH}}


            - name: 'Terraform format'
              uses: hashicorp/terraform-github-action@master
              with:
                tf_action_version: 1.7.5
                tf_action_subcommand: 'init'
                tf_action_working_dir: ${{env.ROOTH_PATH}}

            - name: 'Terraform format'
              uses: hashicorp/terraform-github-action@master
              with:
                tf_action_version: 1.7.5
                tf_action_subcommand: 'plan'
                tf_action_working_dir: ${{env.ROOTH_PATH}}

            - name: 'Terraform format'
              uses: hashicorp/terraform-github-action@master
              with:
                tf_action_version: 1.7.5
                tf_action_subcommand: 'apply'
                tf_action_working_dir: ${{env.ROOTH_PATH}}
                         

